maven_jar(
  name = 'junit',
  id = 'junit:junit:4.11',
  sha1 = '4e031bb61df09069aeb2bffb4019e7a5034a4ee0',
  deps = [':hamcrest-core'],
)

maven_jar(
  name = 'hamcrest-core',
  id = 'org.hamcrest:hamcrest-core:1.3',
  sha1 = '42a25dc3219429f0e5d060061f71acb49bf010a0',
  visibility = ['//lib/junit:junit'],
)
