package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "junit",
    exports = ["@junit//jar"],
)

java_library(
    name = "hamcrest-core",
    exports = ["@hamcrest-core//jar"],
)
