maven_jar(
  name = 'soy',
  id = 'com.google.template:soy:2015-04-10',
  sha1 = 'f2a260c0eafbc5756ccec546efd2ffd5b0a583cb',
  deps = [
    ':icu4j',
    '//lib:jsr305',
  ],
)

maven_jar(
  name = 'icu4j',
  id = 'com.ibm.icu:icu4j:51.1',
  sha1 = '8ce396c4aed83c0c3de9158dc72c834fd283d5a4',
)
