# Keep this version of Soy synchronized with the version used in Gerrit.
maven_jar(
  name = 'soy',
  id = 'com.google.template:soy:2016-08-09',
  sha1 = '43d33651e95480d515fe26c10a662faafe3ad1e4',
  deps = [
    ':icu4j',
    '//lib:jsr305',
  ],
)

maven_jar(
  name = 'icu4j',
  id = 'com.ibm.icu:icu4j:57.1',
  sha1 = '198ea005f41219f038f4291f0b0e9f3259730e92',
)
