package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "soy",
    exports = [
        "@soy//jar",
    ],
    runtime_deps = [
        "@html_types//jar",
        "@icu4j//jar",
        "@protobuf//jar",
    ],
)
