package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "soy",
    exports = [
      "@soy//jar",
    ],
    runtime_deps = [
      "@icu4j//jar",
      "@html_types//jar",
      "@protobuf//jar",
    ],
)
