SRCS = glob(['src/main/java/**/*.java'])
DEPS = [
  '//lib:guava',
  '//lib/jgit:jgit',
]

java_library(
  name = 'lib',
  srcs = SRCS,
  deps = DEPS,
  visibility = ['PUBLIC'],
)

java_sources(
  name = 'src',
  srcs = SRCS,
  visibility = ['//:'],
)

java_doc(
  name = 'javadoc',
  title = 'Blame Cache API Documentation',
  pkgs = ['com.google.gitiles.blame'],
  paths = ['blame-cache/src/main/java'],
  srcs = SRCS,
  deps = DEPS,
  visibility = ['//:'],
  do_it_wrong = True,
)
