package(
    default_visibility = ["//visibility:public"],
)

[java_library(
    name = n,
    exports = ["@%s//jar" % n.replace("-", "_")],
) for n in [
    "autolink",
    "commonmark",
    "commons-lang3",
    "cm-autolink",
    "gfm-strikethrough",
    "gfm-tables",
    "html-types",
    "jsr305",
    "joda-time",
    "servlet-api_2_5",
    "servlet-api_3_0",
    "truth",
    "gson",
    "guava",
    "prettify",
]]
