java_library(
  name = 'lib',
  srcs = glob(['src/main/java/**/*.java']),
  deps = [
    '//blame-cache:lib',
    '//gitiles-servlet:servlet',
    '//lib:guava',
    '//lib:servlet-api_3_0',
    '//lib/jgit:jgit',
    '//lib/jgit:jgit-servlet',
    '//lib/jetty:server',
    '//lib/jetty:servlet',
    '//lib/slf4j:slf4j-api',
    '//lib/slf4j:slf4j-simple',
    '//lib/soy:soy',
  ],
  visibility = ['PUBLIC'],
)

java_binary(
  name = 'dev',
  deps = [':lib'],
  main_class = 'com.google.gitiles.dev.Main',
  visibility = ['PUBLIC'],
)
