VERS = '1.7.7'

maven_jar(
  name = 'slf4j-api',
  id = 'org.slf4j:slf4j-api:' + VERS,
  sha1 = '2b8019b6249bb05d81d3a3094e468753e2b21311',
  visibility = ['PUBLIC'],
)


maven_jar(
  name = 'slf4j-simple',
  id = 'org.slf4j:slf4j-simple:' + VERS,
  sha1 = '8095d0b9f7e0a9cd79a663c740e0f8fb31d0e2c8',
  deps = [':slf4j-api'],
  visibility = ['PUBLIC'],
)
